# Generated by Django 5.2.4 on 2025-08-18 20:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidade_medida', models.CharField(choices=[('g', 'Gramas (g)'), ('kg', 'Quilos (kg)'), ('ml', 'Mililitros (ml)'), ('l', 'Litros (l)'), ('un', 'Unidade'), ('fatia', 'Fatia'), ('pitada', 'Pitada')], default='kg', max_length=10)),
                ('preco_compra_atual_centavos', models.IntegerField(default=0, help_text='Preço em centavos (ex: 2550 = R$ 25,50)')),
                ('data_ultima_compra', models.DateField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ingrediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='ingredientes.ingrediente')),
            ],
            options={
                'verbose_name': 'Estoque de Ingrediente',
                'verbose_name_plural': 'Estoque de Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='autenticacao.pizzaria')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
                'unique_together': {('pizzaria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='CompraIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('preco_unitario_centavos', models.IntegerField(help_text='Preço por unidade em centavos (ex: 2550 = R$ 25,50/kg)')),
                ('valor_total_centavos', models.IntegerField(help_text='Valor total da compra em centavos')),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
                ('numero_nota', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='ingredientes.ingrediente')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor')),
            ],
            options={
                'verbose_name': 'Compra de Ingrediente',
                'verbose_name_plural': 'Compras de Ingredientes',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPrecoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_centavos', models.IntegerField(help_text='Preço em centavos')),
                ('data_preco', models.DateField()),
                ('fornecedor', models.CharField(max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.compraingrediente')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='ingredientes.ingrediente')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Histórico de Preços',
                'ordering': ['-data_preco'],
            },
        ),
    ]
