# Generated by Django 5.2.4 on 2025-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueingrediente',
            name='unidade_medida',
            field=models.CharField(choices=[('g', 'Gramas (g)'), ('kg', 'Quilos (kg)'), ('un', 'Unidade')], default='kg', max_length=10),
        ),
    ]
