# Generated by Django 5.2.4 on 2025-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_converter_unidades_antigas'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraingrediente',
            name='unidade',
            field=models.CharField(choices=[('g', 'Gramas (g)'), ('kg', 'Quilos (kg)'), ('un', 'Unidade')], default='kg', help_text='Unidade da quantidade comprada', max_length=10),
        ),
    ]
