# Generated by Django 5.2.4 on 2025-09-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_adicionar_unidade_compra'),
        ('ingredientes', '0001_initial'),
        ('pedidos', '0003_pedido_estoque_baixado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoUsoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidade', models.CharField(choices=[('g', 'Gramas (g)'), ('kg', 'Quilos (kg)'), ('un', 'Unidade')], max_length=10)),
                ('estoque_antes', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estoque_depois', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_utilizacao', models.DateTimeField(auto_now_add=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_usos', to='ingredientes.ingrediente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_ingredientes', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Uso de Ingrediente',
                'verbose_name_plural': 'Usos de Ingredientes',
                'ordering': ['-data_utilizacao'],
            },
        ),
    ]
