services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: pizzaria_postgres
    environment:
      POSTGRES_DB: pizzaria_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"  # Porta 5433 no host, 5432 no container
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # SQL inicial (opcional)
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicação Django (para futuro uso)
  # web:
  #   build: .
  #   container_name: pizzaria_web
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB_HOST=postgres

volumes:
  postgres_data:
