# Generated by Django 5.2.4 on 2025-08-06 20:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no cardápio')),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produto', to='autenticacao.pizzaria')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produto',
                'ordering': ('ordem', 'nome'),
                'unique_together': {('pizzaria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('tempo_preparo_minutos', models.PositiveIntegerField(default=15)),
                ('disponivel', models.BooleanField(default=True)),
                ('vegetariano', models.BooleanField(default=False)),
                ('vegano', models.BooleanField(default=False)),
                ('contem_gluten', models.BooleanField(default=False)),
                ('contem_lactose', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoriaproduto')),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='autenticacao.pizzaria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('nome',),
                'unique_together': {('pizzaria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='PrecoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Preço de Produto',
                'verbose_name_plural': 'Preços de Produto',
                'ordering': ('-data_inicio',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('data_fim__isnull', True)), fields=('produto',), name='produto_preco_unico_vigente')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(blank=True, help_text='Ex.: 200g, 2 colheres. Opcional', max_length=50)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_produtos', to='ingredientes.ingrediente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_ingredientes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Ingrediente do Produto',
                'verbose_name_plural': 'Ingredientes do Produto',
                'unique_together': {('produto', 'ingrediente')},
            },
        ),
    ]
