# Generated by Django 5.2.4 on 2025-08-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoingrediente',
            name='unidade',
            field=models.CharField(choices=[('g', 'Gramas (g)'), ('kg', 'Quilos (kg)'), ('ml', 'Mililitros (ml)'), ('l', 'Litros (l)'), ('un', 'Unidade'), ('fatia', 'Fatia'), ('pitada', 'Pitada')], default='g', help_text='Unidade de medida', max_length=10),
        ),
        migrations.AlterField(
            model_name='produtoingrediente',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade do ingrediente', max_digits=8),
        ),
    ]
