# Generated by Django 5.2.4 on 2025-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtoingrediente_unidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precoproduto',
            name='valor',
        ),
        migrations.AddField(
            model_name='precoproduto',
            name='preco_base_centavos',
            field=models.IntegerField(default=0, help_text='Preço base em centavos (ex: 3200 = R$ 32,00)'),
        ),
        migrations.AddField(
            model_name='precoproduto',
            name='preco_custo_centavos',
            field=models.IntegerField(default=0, help_text='Preço de custo em centavos (calculado automaticamente)'),
        ),
        migrations.AddField(
            model_name='precoproduto',
            name='preco_venda_centavos',
            field=models.IntegerField(default=0, help_text='Preço de venda em centavos (ex: 3550 = R$ 35,50)'),
        ),
    ]
