# Generated by Django 5.2.4 on 2025-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_precoproduto_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoingrediente',
            name='unidade',
            field=models.CharField(choices=[('g', 'Gramas (g)'), ('kg', 'Quilos (kg)'), ('un', 'Unidade')], default='g', help_text='Unidade de medida', max_length=10),
        ),
    ]
