# Generated by Django 5.2.4 on 2025-08-16 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('produtos', '0002_produtoingrediente_unidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, max_length=120)),
                ('cliente_telefone', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('forma_pagamento', models.CharField(choices=[('DIN', 'Dinheiro'), ('PIX', 'Pix'), ('CC', 'Cartão Crédito'), ('CD', 'Cartão Débito')], max_length=3)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('RECEBIDO', 'Recebido'), ('EM_PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='RECEBIDO', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='autenticacao.pizzaria')),
            ],
            options={
                'ordering': ('-data_criacao',),
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacao_item', models.CharField(blank=True, max_length=255)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
