# Generated by Django 5.2.4 on 2025-09-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estoque_baixado',
            field=models.BooleanField(default=False),
        ),
    ]
