# Generated by Django 5.2.4 on 2025-08-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do ingrediente.')),
                ('vegetariano', models.BooleanField(default=False)),
                ('vegano', models.BooleanField(default=False)),
                ('contem_gluten', models.BooleanField(default=False)),
                ('contem_lactose', models.BooleanField(default=False)),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='autenticacao.pizzaria')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nome'],
                'unique_together': {('pizzaria', 'nome')},
            },
        ),
    ]
