# Generated by Django 5.2.4 on 2025-08-20 01:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('estoque', '0004_adicionar_unidade_compra'),
        ('pedidos', '0002_pedido_cliente'),
        ('produtos', '0005_converter_unidades_antigas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DespesaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_centavos', models.IntegerField(help_text='Valor em centavos (ex: 15000 = R$ 150,00)', validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(choices=[('FIXA', 'Despesa Fixa'), ('VARIAVEL', 'Despesa Variável')], max_length=10)),
                ('forma_pagamento', models.CharField(choices=[('DIN', 'Dinheiro'), ('PIX', 'Pix'), ('TED', 'TED/DOC'), ('CC', 'Cartão Crédito'), ('CD', 'Cartão Débito'), ('BOL', 'Boleto'), ('DEB', 'Débito Automático')], max_length=3)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='autenticacao.pizzaria')),
                ('tipo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='financeiro.tipodespesa')),
            ],
            options={
                'verbose_name': 'Despesa Operacional',
                'verbose_name_plural': 'Despesas Operacionais',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('origem', models.CharField(choices=[('VENDA', 'Venda (Pedido)'), ('DESPESA', 'Despesa Operacional'), ('COMPRA', 'Compra de Estoque'), ('AJUSTE', 'Ajuste Manual'), ('OUTROS', 'Outros')], max_length=10)),
                ('descricao', models.CharField(max_length=200)),
                ('valor_centavos', models.IntegerField(help_text='Valor em centavos (ex: 5500 = R$ 55,00)', validators=[django.core.validators.MinValueValidator(1)])),
                ('forma_pagamento', models.CharField(choices=[('DIN', 'Dinheiro'), ('PIX', 'Pix'), ('TED', 'TED/DOC'), ('CC', 'Cartão Crédito'), ('CD', 'Cartão Débito'), ('BOL', 'Boleto'), ('DEB', 'Débito Automático')], max_length=3)),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='estoque.compraingrediente')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.despesaoperacional')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='pedidos.pedido')),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_caixa', to='autenticacao.pizzaria')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='MetaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_meta', models.CharField(choices=[('RECEITA', 'Meta de Receita'), ('QUANTIDADE', 'Meta de Quantidade'), ('TICKET', 'Meta de Ticket Médio')], max_length=12)),
                ('meta_receita_centavos', models.IntegerField(default=0, help_text='Meta de receita em centavos')),
                ('meta_quantidade', models.IntegerField(default=0, help_text='Meta de quantidade de pedidos')),
                ('meta_ticket_medio_centavos', models.IntegerField(default=0, help_text='Meta de ticket médio em centavos')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(12)])),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas', to='produtos.categoriaproduto')),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_vendas', to='autenticacao.pizzaria')),
            ],
            options={
                'verbose_name': 'Meta de Venda',
                'verbose_name_plural': 'Metas de Vendas',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('pizzaria', 'nome', 'mes', 'ano')},
            },
        ),
    ]
