# Generated by Django 5.2.4 on 2025-08-20 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('financeiro', '0002_alter_metavenda_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_centavos', models.IntegerField(help_text='Valor em centavos (ex: 15000 = R$ 150,00)', validators=[django.core.validators.MinValueValidator(1)])),
                ('dia_vencimento', models.IntegerField(help_text='Dia do mês para vencimento (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('forma_pagamento', models.CharField(choices=[('DIN', 'Dinheiro'), ('PIX', 'Pix'), ('TED', 'TED/DOC'), ('CC', 'Cartão Crédito'), ('CD', 'Cartão Débito'), ('BOL', 'Boleto'), ('DEB', 'Débito Automático')], max_length=3)),
                ('observacoes', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True, help_text='Se a despesa recorrente está ativa')),
                ('data_inicio', models.DateField(help_text='Data de início da recorrência')),
                ('data_fim', models.DateField(blank=True, help_text='Data de fim da recorrência (deixe em branco para indefinido)', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_recorrentes', to='autenticacao.pizzaria')),
                ('tipo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_recorrentes', to='financeiro.tipodespesa')),
            ],
            options={
                'verbose_name': 'Despesa Recorrente',
                'verbose_name_plural': 'Despesas Recorrentes',
                'ordering': ['dia_vencimento', 'descricao'],
            },
        ),
    ]
