# Generated by Django 5.2.4 on 2025-08-20 17:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('financeiro', '0003_despesarecorrente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metavenda',
            options={'ordering': ['-ano', '-mes'], 'verbose_name': 'Meta de Venda', 'verbose_name_plural': 'Metas de Venda'},
        ),
        migrations.AlterUniqueTogether(
            name='metavenda',
            unique_together={('pizzaria', 'ano', 'mes')},
        ),
        migrations.RemoveField(
            model_name='movimentacaocaixa',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='data_fim_recorrencia',
            field=models.DateField(blank=True, help_text='Data de fim da recorrência (deixe em branco para indefinido)', null=True),
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='data_inicio_recorrencia',
            field=models.DateField(blank=True, help_text='Data de início da recorrência mensal', null=True),
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='dia_vencimento_recorrente',
            field=models.IntegerField(blank=True, help_text='Dia do mês para vencimento (1-31) - apenas para despesas recorrentes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='despesaoperacional',
            name='recorrente',
            field=models.BooleanField(default=False, help_text='Se esta despesa se repete mensalmente'),
        ),
        migrations.AlterField(
            model_name='metavenda',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='metavenda',
            name='meta_receita_centavos',
            field=models.IntegerField(help_text='Meta de receita em centavos', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='metavenda',
            name='meta_ticket_medio_centavos',
            field=models.IntegerField(help_text='Meta de ticket médio em centavos', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='metavenda',
            name='pizzaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_venda', to='autenticacao.pizzaria'),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='data_movimentacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='origem',
            field=models.CharField(choices=[('VENDA', 'Venda'), ('COMPRA', 'Compra de Estoque'), ('DESPESA', 'Despesa Operacional'), ('OUTROS', 'Outros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='pizzaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='autenticacao.pizzaria'),
        ),
        migrations.AlterField(
            model_name='movimentacaocaixa',
            name='valor_centavos',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='DespesaRecorrente',
        ),
        migrations.RemoveField(
            model_name='metavenda',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='metavenda',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='metavenda',
            name='meta_quantidade',
        ),
        migrations.RemoveField(
            model_name='metavenda',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='metavenda',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='metavenda',
            name='tipo_meta',
        ),
    ]
