# Generated by Django 5.2.4 on 2025-08-04 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pizzaria',
                'verbose_name_plural': 'Pizzarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPizzaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('super_admin', 'Super Admin'), ('dono_pizzaria', 'Dono da Pizzaria')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pizzaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_pizzaria', to='autenticacao.pizzaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_pizzaria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário Pizzaria',
                'verbose_name_plural': 'Usuários Pizzaria',
                'ordering': ['usuario__username'],
                'unique_together': {('usuario', 'pizzaria')},
            },
        ),
    ]
