# Generated by Django 5.2.4 on 2025-08-17 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pizzaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='autenticacao.pizzaria')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Casa, Trabalho', max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('referencia', models.CharField(blank=True, help_text='Ponto de referência', max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Endereço do Cliente',
                'verbose_name_plural': 'Endereços dos Clientes',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_principal', to='clientes.enderecocliente'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('pizzaria', 'telefone')},
        ),
    ]
